name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx nbsphinx myst_nb sphinx_copybutton pydata_sphinx_theme # Add any other dependencies your docs need

    - name: Build Sphinx documentation
      run: |
        cd docs  # Adjust this if your Sphinx files are in a different directory
        make clean  # Start with a clean build
        sphinx-apidoc -f -o . ../src/dynamicAll --separate
        make html
        touch _build/html/.nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files/folders that start with an underscore
        touch _build/.nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files/folders that start with an underscore
        touch .nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files/folders that start with an underscore

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # Adjust this path if necessary