name: Build and Deploy Sphinx Docs
on:
  push:
    branches:
      - main # or your default branch name
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you're using
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx nbsphinx myst_nb sphinx_copybutton pydata_sphinx_theme
          pip install jax jaxopt emcee corner
          pip scipy astropy numpyro matplotlib arviz astroquery scikit-learn
          pip freeze > installed_packages.txt
          cat installed_packages.txt
      - name: Environment Info
        run: |
          python --version
          sphinx-build --version
          echo $PYTHONPATH
      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          sphinx-apidoc -f -o . ../src/dynamicAll --separate
          sphinx-build -b html . _build/html -v -v > build_log.txt 2>&1
          cat build_log.txt
          make html
          touch _build/html/.nojekyll
      - name: Check for py-modindex.html
        run: |
          cd docs/_build/html
          ls -la
          if [ -f "py-modindex.html" ]; then
            echo "py-modindex.html exists"
            head -n 20 py-modindex.html
          else
            echo "py-modindex.html does not exist"
          fi
      - name: Check source structure
        run: |
          cd src
          find . -type d -or -name "*.py"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html # Adjust this path if necessary