name: Build and Deploy Sphinx Docs
on:
  push:
    branches:
      - main # or your default branch name
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you're using
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx nbsphinx myst_nb sphinx_copybutton pydata_sphinx_theme
          pip install jax jaxopt emcee corner
          pip install scipy astropy numpyro matplotlib arviz astroquery scikit-learn
          pip freeze > installed_packages.txt
          cat installed_packages.txt
      - name: Environment Info
        run: |
          python --version
          sphinx-build --version
          echo $PYTHONPATH
      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          sphinx-apidoc -f -o . ../src/dynamicAll --separate
          make html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html # Adjust this path if necessary